<?php

/** * Implements hook_block_info(). */
function canary_blocks_block_info() {
  $blocks = array();
  $blocks['canary_address']    = array('info' => t('Canary Address') );
  $blocks['svg_logo']          = array('info' => t('SVG Logo') );
  $blocks['footer_logo_title'] = array('info' => t('Footer Logo Title') );
  return $blocks;
}

/*** Implements hook_block_view().*/
function canary_blocks_block_view($block_name = '') {


  // SVG LOGO
  if ($block_name == 'svg_logo') {
    $svg_logo = drupal_get_path('theme', 'feather') . '/includes/logo-svg.inc';
    $block_content = <<<BLOCK
       <a href="/" class="logo-site-name">
         <div class="logo">
BLOCK;
    $block_content .= file_get_contents($svg_logo);
    $block_content .= <<<BLOCK
         </div>
         <h1 class="site-name">Canary Promotion</h1>
       </a>
       <p class="tagline">
         Communications for Arts, Culture
         <span class="amp">&amp;</span>
         Mission-Driven Clients
       </p>
BLOCK;
    $block = array( 'subject' => t(''), 'content' => $block_content);
    return $block;
  }

  // FOOTER LOGO TITLE
  if ($block_name == 'footer_logo_title') {
    $svg_logo = drupal_get_path('theme', 'feather') . '/includes/logo-svg.inc';
    $block_content = <<<BLOCK
       <a href="/" class="footer-logo-site-name">
         <div class="footer-logo">
BLOCK;
    $block_content .= file_get_contents($svg_logo);
    $block_content .= <<<BLOCK
         </div>
        <div class="footer-site-name">Canary Promotion</div>
      </a>
BLOCK;
    $block = array( 'subject' => t(''), 'content' => $block_content);
    return $block;
  }


  // CANARY ADDRESS
  if ($block_name == 'canary_address') {
    $copyright_date = date("Y");
    $block_content = <<<BLOCK
    <section class="address">
      <h1>Our Address</h1>
      <div id="canary-vcard" class="vcard">
      <div class="adr">
        <div class="street-address">24 E Glenside Ave, 1st Floor</div>
        <span class="locality">Glenside</span>
        ,
        <span class="region">PA</span>
        ,
        <span class="postal-code">19038</span>
        <span class="country-name">USA</span>
      </div>
      <div class="map">
        <a href="http://maps.google.com/maps?hl=en&amp;q=24+E+Glenside+Ave,+1st+Floor+Glenside+,+PA+,+19038&amp;ie=UTF8&amp;hq=&amp;hnear=24+E+Glenside+Ave,+Glenside,+Montgomery,+Pennsylvania+19038&amp;gl=us&amp;ei=mhHfS92bGISClAfJsNTnBA&amp;ved=0CAkQ8gEwAA&amp;z=16">Google Map</a>
      </div>
      <div class="tel">(215) 690-4065</div>
      <div class="email">
        <a href="mailto:info@canarypromo.com">info@canarypromo.com</a>
      </div>
    </div>
    <div class="lc">
      <p class="copyright">&copy; 2001 &mdash; $copyright_date Canary Promotion. All rights reserved.</p>
    </div>
    </section>
BLOCK;
    $block = array( 'subject' => t(''), 'content' => $block_content);
    return $block;
  }


}
